---
title: "COVID-19 Visualization"
author: "Chong Zhang"
date: "2021-04-01T00:00:00-07:00"
output:
  pdf_document: default
urlcolor: blue
header-includes:    
  - \usepackage{lastpage}
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancyhead[CO, CE]{Chong Zhang}
  - \fancyfoot[CO, CE]{\thepage \ of \pageref{LastPage}}
---

```{r setup, message = FALSE, echo=FALSE}
# Students: You probably shouldn't change any of the code in this chunk.

# These are the packages you will need for this activity
packages_needed <- c("tidyverse", "googledrive", "readxl", "janitor", 
                     "lubridate", "opendatatoronto", "ggthemes")

package.check <- lapply(
  packages_needed,
  FUN = function(x) {
    if (!require(x, character.only = TRUE)) {
      install.packages(x, dependencies = TRUE)
    }
  }
)

# Credit: package.check based on a helpful post from Vikram Baliga https://vbaliga.github.io/verify-that-r-packages-are-installed-and-loaded/

# Load tidyverse
library(tidyverse)
library(readxl)
library(janitor)
library(opendatatoronto)
library(ggthemes)

# Set so that long lines in R will be wrapped:
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=80), echo = FALSE)
```


```{r getdata, eval = FALSE, echo=FALSE}
# Students: You probably shouldn't change any of the code in this chunk BUT...

# This chunk loads the most recent data from Toronto City and the data from OpenToronto.

# You have to RUN this chunk by hand to update the data as 
#   eval is set to FALSE to limit unnecessary requsts on the site.

###################################################
# Step one: Get the COVID data from Toronto City. #
###################################################

googledrive::drive_deauth()

url1 <- "https://drive.google.com/file/d/11KF1DuN5tntugNc10ogQDzFnW05ruzLH/view"
googledrive::drive_download(url1, path="data/CityofToronto_COVID-19_Daily_Public_Reporting.xlsx", overwrite = TRUE)

url2 <- "https://drive.google.com/file/d/1jzH64LvFQ-UsDibXO0MOtvjbL2CvnV3N/view"
googledrive::drive_download(url2, path = "data/CityofToronto_COVID-19_NeighbourhoodData.xlsx", overwrite = TRUE)

# this removes the url object that we don't need anymore
rm(url1, url2)

#####################################################################
# Step two: Get the data neighbourhood data from Open Data Toronto. #
#####################################################################

nbhoods_shape_raw <- list_package_resources("neighbourhoods") %>% 
  get_resource()

saveRDS(nbhoods_shape_raw, "data/neighbourhood_shapefile.Rds")

nbhood_profile <- search_packages("Neighbourhood Profile") %>%
  list_package_resources() %>% 
  filter(name == "neighbourhood-profiles-2016-csv") %>% 
  get_resource()

saveRDS(nbhood_profile, "data/neighbourhood_profile.Rds")
```


```{r load_data, echo=FALSE}
######################################################
# Step three: Load the COVID data from Toronto City. #
######################################################

# Saving the name of the file as an object and then using the object name in the
# following code is a helpful practice. Why? If we change the name of the file 
# being used, we'll only have to change it in one place. This helps us avoid 
# 'human error'.

daily_data <- "data/CityofToronto_COVID-19_Daily_Public_Reporting.xlsx"

# Cases reported by date (double check the sheet is correct)
# Should be a sheet names something like  
## 'Cases by Reported Date'
reported_raw <- read_excel(daily_data, sheet = 5) %>% 
  clean_names()

# Cases by outbreak type (double check the sheet is correct)
# Should be a sheet names something like  
## 'Cases by Outbreak Type and Epis'
outbreak_raw <- read_excel(daily_data, sheet = 3) %>% 
  clean_names()

# When was this data updated?
date_daily <- read_excel(daily_data, sheet = 1) %>% 
  clean_names()

# By neighbourhood
neighbourood_data <- "data/CityofToronto_COVID-19_NeighbourhoodData.xlsx"

# Cases reported by date
nbhood_raw <- read_excel(neighbourood_data, sheet = 2) %>% 
  clean_names()

# Date the neighbourhood data was last updated
date_nbhood <- read_excel(neighbourood_data, sheet = 1) %>% 
  clean_names()

#don't need these anymore
rm(daily_data, neighbourood_data)

#############################################################
# Step four: Load the neighbourhood data from Toronto City. #
#############################################################

# Get neighbourhood profile data
nbhood_profile <- readRDS("data/neighbourhood_profile.Rds")

# Get shape data for mapping 
nbhoods_shape_raw <- readRDS("data/neighbourhood_shapefile.Rds") %>% 
  sf::st_as_sf() ## Makes sure shape info is in the most up to date format

```

Code last run `r Sys.Date()`.  
Daily: `r date_daily[1,1]`.   
Neighbourhood: `r date_nbhood[1,1]`. 

# Task 1: Daily cases
## Data wrangling

```{r cases_dw,echo= T}
reported<- reported_raw%>%
  mutate_if(is.numeric,replace_na,replace=0)%>%
  mutate(reported_date=date(reported_date))%>%
  pivot_longer( -c(reported_date),names_to= "status",values_to='count')%>%
  mutate(status=str_to_sentence(status))%>%
  mutate(status=fct_relevel(status,'Recovered',after=1))

#reported[is.na(reported)] <- 0
```

\newpage
## Data visualization

```{r cases_vis,echo= T}
reported%>%
  ggplot(aes(x=reported_date,y=count,fill=status))+
  geom_bar(stat = 'identity')+theme_minimal()+
  labs(title="Cases reported by day in Toronto, Canada",
       subtitle = "Confirmed and probable cases",
       x="Reported date",
       y="Case count",
       caption = str_c("Created by: Chong Zhang for STA303/1002,U of T\n Source: Ontario Ministry of Health, Integrated  Public Health Information System and CORES\n",date_daily[1,1]))+
  theme(legend.title = element_blank(),legend.position = c(0.15,0.8))+
  scale_x_date(labels=scales::date_format("%d %b %y"),limits = c(date("2020-01-01")
                                                                 ,Sys.Date()))+
  scale_y_continuous(limits  = c(0,2000))+
  scale_fill_manual(values = c("#003F5C","#86BCB6","#B9CA5D" ))

```

\newpage
# Task 2: Outbreak type
## Data wrangling


```{r outbreak_dw, echo= T}
outbreak<-outbreak_raw%>%
  mutate(episode_week=date(episode_week))%>%
  mutate(outbreak_or_sporadic = str_replace(outbreak_raw$outbreak_or_sporadic,"OB Associated","Outbreak associated"))%>%
  mutate(outbreak_or_sporadic= fct_relevel(outbreak_or_sporadic,'Outbreak associated',after=1))%>%
  group_by(episode_week)
outbreak1<-outbreak_raw%>%
  group_by(episode_week)%>%summarise(total_cases=sum(cases),.groups="drop")
```

\newpage
## Data visualization

```{r outbreak_vis,echo=T}
outbreak%>%
  ggplot(aes(x=episode_week,y=cases,fill=outbreak_or_sporadic))+
  geom_bar(stat = 'identity')+theme_minimal()+
  labs(title="Cases by outbreak type and week in Toronto, Canada",
       subtitle = "Confirmed and probable cases",
       x="Episode Week",
       y="Case count",
       caption = str_c("Created by: Chong Zhang for STA303/1002,U of T\nSource: Ontario Ministry of Health, Integrated Public Health Information System and CORES\n",date_daily[1,1]))+
  theme(legend.title = element_blank(),legend.position = c(0.15,0.8))+
  scale_x_date(labels=scales::date_format("%d %b %y"),limits = c(date("2020-01-01")
                                                                 ,Sys.Date()))+
  scale_y_continuous(limits  = c(0,max(outbreak1$total_cases)))+
  scale_fill_manual(values = c("#86BCB6","#B9CA5D"))
```

\newpage
# Task 3: Neighbourhoods
## Data wrangling: part 1

```{r nbhood_dw_1,echo=T}
income <- nbhood_profile %>%
  filter(`_id`==1143) %>%
  pivot_longer(-c(`_id`,Category,Topic,`Data Source`, Characteristic),names_to = "neighbourhood_name",values_to="percentage") %>%
  mutate(percentage=parse_number(percentage))

```

## Data wrangling: part 2

```{r nbhood_dw_2,echo=T}
nbhoods_shape_raw$AREA_NAME[nbhoods_shape_raw$`_id`==10681]<-"Weston-Pelham Park (91)"
nbhoods_shape_raw$AREA_NAME[nbhoods_shape_raw$`_id`==10755]<-"Cabbagetown-South St. James Town (71)"
nbhoods_shape_raw$AREA_NAME[nbhoods_shape_raw$`_id`==10659]<-"North St. James Town (74)"
nbhoods_all<-nbhoods_shape_raw%>%
  mutate(neighbourhood_name =str_remove(nbhoods_shape_raw$AREA_NAME ,"\\s\\(\\d+\\)$"))%>%
  left_join(income,by="neighbourhood_name") %>%
  left_join(nbhood_raw,by="neighbourhood_name") %>%
  rename(rate_per_100000=rate_per_100_000_people)
```

